
// ===================================================================
// DESC: Comprehensive Bytecode Generation Test Suite (25+ tests)
// ===================================================================
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include "../../compiler/codegen/codegen.h"
#include "../../vm/bci_chunk.h"
#include "../../vm/bci_vm.h"

static int tests_run = 0;
static int tests_passed = 0;
static int tests_failed = 0;

#define TEST(name) \
    do { \
        tests_run++; \
        printf("Test %d: %s...", tests_run, name); \
        fflush(stdout);

#define TEST_END \
        tests_passed++; \
        printf(" PASSED\n"); \
    } while(0)

#define TEST_FAIL(msg) \
    do { \
        tests_failed++; \
        printf(" FAILED: %s\n", msg); \
        return; \
    } while(0)

#define ASSERT_TRUE(cond, msg) \
    if (!(cond)) TEST_FAIL(msg)

#define ASSERT_FALSE(cond, msg) \
    if (cond) TEST_FAIL(msg)

#define ASSERT_EQ(a, b, msg) \
    if ((a) != (b)) TEST_FAIL(msg)

#define ASSERT_DOUBLE_EQ(a, b, msg) \
    if (fabs((a) - (b)) > 0.0001) TEST_FAIL(msg)

// Helper: Create a simple literal node
static AstNode* create_literal_node(double value) {
    AstNode* node = malloc(sizeof(AstNode));
    node->kind = AST_NODE_LITERAL;
    node->as.literal.type = NULL;
    node->as.literal.value.f64 = value;
    return node;
}

// Helper: Create a binary op node
static AstNode* create_binary_op_node(const char* op, AstNode* left, AstNode* right) {
    AstNode* node = malloc(sizeof(AstNode));
    node->kind = AST_NODE_BINARY_OP;
    node->as.binary_op.op = op;
    node->as.binary_op.left = left;
    node->as.binary_op.right = right;
    return node;
}

// Helper: Free AST node
static void free_ast_node(AstNode* node) {
    if (!node) return;
    
    if (node->kind == AST_NODE_BINARY_OP) {
        free_ast_node(node->as.binary_op.left);
        free_ast_node(node->as.binary_op.right);
    }
    
    free(node);
}

// ============================================================================
// TEST 1: Code Generator Creation and Destruction
// ============================================================================
void test_codegen_create_destroy(void) {
    TEST("codegen_create_destroy");
    
    CodeGenerator* codegen = codegen_create();
    ASSERT_TRUE(codegen != NULL, "Failed to create code generator");
    ASSERT_FALSE(codegen->had_error, "New codegen should not have errors");
    ASSERT_EQ(codegen->global_count, 0, "New codegen should have 0 globals");
    
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 2: Generate Bytecode for Simple Literal
// ============================================================================
void test_generate_literal(void) {
    TEST("generate_literal");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    AstNode* node = create_literal_node(42.0);
    
    bool success = codegen_generate(codegen, node, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_FALSE(codegen->had_error, "Codegen reported error");
    
    // Check generated bytecode
    ASSERT_TRUE(chunk.count >= 3, "Expected at least 3 bytes");
    ASSERT_EQ(chunk.code[0], OPCODE_CONSTANT, "Expected CONSTANT opcode");
    ASSERT_EQ(chunk.constants.len, 1, "Expected 1 constant");
    ASSERT_DOUBLE_EQ(chunk.constants.data[0], 42.0, "Expected constant value 42.0");
    
    free_ast_node(node);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 3: Generate Bytecode for Addition
// ============================================================================
void test_generate_addition(void) {
    TEST("generate_addition");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 10 + 20
    AstNode* left = create_literal_node(10.0);
    AstNode* right = create_literal_node(20.0);
    AstNode* add = create_binary_op_node("+", left, right);
    
    bool success = codegen_generate(codegen, add, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    
    // Check bytecode: CONSTANT 10, CONSTANT 20, ADD, RETURN
    ASSERT_TRUE(chunk.count >= 6, "Expected at least 6 bytes");
    ASSERT_EQ(chunk.code[0], OPCODE_CONSTANT, "Expected CONSTANT");
    ASSERT_EQ(chunk.code[2], OPCODE_CONSTANT, "Expected CONSTANT");
    ASSERT_EQ(chunk.code[4], OPCODE_ADD, "Expected ADD");
    
    free_ast_node(add);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 4: Generate Bytecode for Subtraction
// ============================================================================
void test_generate_subtraction(void) {
    TEST("generate_subtraction");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 50 - 30
    AstNode* left = create_literal_node(50.0);
    AstNode* right = create_literal_node(30.0);
    AstNode* sub = create_binary_op_node("-", left, right);
    
    bool success = codegen_generate(codegen, sub, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_SUBTRACT, "Expected SUBTRACT");
    
    free_ast_node(sub);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 5: Generate Bytecode for Multiplication
// ============================================================================
void test_generate_multiplication(void) {
    TEST("generate_multiplication");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 6 * 7
    AstNode* left = create_literal_node(6.0);
    AstNode* right = create_literal_node(7.0);
    AstNode* mul = create_binary_op_node("*", left, right);
    
    bool success = codegen_generate(codegen, mul, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_MULTIPLY, "Expected MULTIPLY");
    
    free_ast_node(mul);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 6: Generate Bytecode for Division
// ============================================================================
void test_generate_division(void) {
    TEST("generate_division");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 100 / 4
    AstNode* left = create_literal_node(100.0);
    AstNode* right = create_literal_node(4.0);
    AstNode* div = create_binary_op_node("/", left, right);
    
    bool success = codegen_generate(codegen, div, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_DIVIDE, "Expected DIVIDE");
    
    free_ast_node(div);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 7: Generate Bytecode for Modulo
// ============================================================================
void test_generate_modulo(void) {
    TEST("generate_modulo");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 17 % 5
    AstNode* left = create_literal_node(17.0);
    AstNode* right = create_literal_node(5.0);
    AstNode* mod = create_binary_op_node("%", left, right);
    
    bool success = codegen_generate(codegen, mod, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_MODULO, "Expected MODULO");
    
    free_ast_node(mod);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 8: Generate Bytecode for Equality Comparison
// ============================================================================
void test_generate_equality(void) {
    TEST("generate_equality");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 5 == 5
    AstNode* left = create_literal_node(5.0);
    AstNode* right = create_literal_node(5.0);
    AstNode* eq = create_binary_op_node("==", left, right);
    
    bool success = codegen_generate(codegen, eq, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_EQUAL, "Expected EQUAL");
    
    free_ast_node(eq);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 9: Generate Bytecode for Inequality Comparison
// ============================================================================
void test_generate_inequality(void) {
    TEST("generate_inequality");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 5 != 10
    AstNode* left = create_literal_node(5.0);
    AstNode* right = create_literal_node(10.0);
    AstNode* neq = create_binary_op_node("!=", left, right);
    
    bool success = codegen_generate(codegen, neq, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_NOT_EQUAL, "Expected NOT_EQUAL");
    
    free_ast_node(neq);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 10: Generate Bytecode for Greater Than
// ============================================================================
void test_generate_greater_than(void) {
    TEST("generate_greater_than");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 10 > 5
    AstNode* left = create_literal_node(10.0);
    AstNode* right = create_literal_node(5.0);
    AstNode* gt = create_binary_op_node(">", left, right);
    
    bool success = codegen_generate(codegen, gt, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_GREATER, "Expected GREATER");
    
    free_ast_node(gt);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 11: Generate Bytecode for Greater Than or Equal
// ============================================================================
void test_generate_greater_equal(void) {
    TEST("generate_greater_equal");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 10 >= 10
    AstNode* left = create_literal_node(10.0);
    AstNode* right = create_literal_node(10.0);
    AstNode* gte = create_binary_op_node(">=", left, right);
    
    bool success = codegen_generate(codegen, gte, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_GREATER_EQUAL, "Expected GREATER_EQUAL");
    
    free_ast_node(gte);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 12: Generate Bytecode for Less Than
// ============================================================================
void test_generate_less_than(void) {
    TEST("generate_less_than");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 3 < 7
    AstNode* left = create_literal_node(3.0);
    AstNode* right = create_literal_node(7.0);
    AstNode* lt = create_binary_op_node("<", left, right);
    
    bool success = codegen_generate(codegen, lt, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_LESS, "Expected LESS");
    
    free_ast_node(lt);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 13: Generate Bytecode for Less Than or Equal
// ============================================================================
void test_generate_less_equal(void) {
    TEST("generate_less_equal");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: 5 <= 5
    AstNode* left = create_literal_node(5.0);
    AstNode* right = create_literal_node(5.0);
    AstNode* lte = create_binary_op_node("<=", left, right);
    
    bool success = codegen_generate(codegen, lte, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_EQ(chunk.code[4], OPCODE_LESS_EQUAL, "Expected LESS_EQUAL");
    
    free_ast_node(lte);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 14: Generate Bytecode for Complex Expression
// ============================================================================
void test_generate_complex_expression(void) {
    TEST("generate_complex_expression");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST: (10 + 20) * (30 - 5)
    AstNode* left_add = create_binary_op_node("+", 
        create_literal_node(10.0), 
        create_literal_node(20.0));
    AstNode* right_sub = create_binary_op_node("-", 
        create_literal_node(30.0), 
        create_literal_node(5.0));
    AstNode* mul = create_binary_op_node("*", left_add, right_sub);
    
    bool success = codegen_generate(codegen, mul, &chunk);
    ASSERT_TRUE(success, "Code generation failed");
    ASSERT_TRUE(chunk.count >= 10, "Expected at least 10 bytes for complex expression");
    
    free_ast_node(mul);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 15: Emit Jump Instruction
// ============================================================================
void test_emit_jump(void) {
    TEST("emit_jump");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    codegen->current_function = function_context_create(NULL, "test");
    codegen->current_function->chunk = &chunk;
    
    int jump_offset = codegen_emit_jump(codegen, OPCODE_JUMP);
    ASSERT_TRUE(jump_offset >= 0, "Jump offset should be non-negative");
    ASSERT_EQ(chunk.code[jump_offset - 1], OPCODE_JUMP, "Expected JUMP opcode");
    
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 16: Patch Jump Instruction
// ============================================================================
void test_patch_jump(void) {
    TEST("patch_jump");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    codegen->current_function = function_context_create(NULL, "test");
    codegen->current_function->chunk = &chunk;
    
    int jump_offset = codegen_emit_jump(codegen, OPCODE_JUMP);
    
    // Emit some instructions
    codegen_emit_byte(codegen, OPCODE_NOP);
    codegen_emit_byte(codegen, OPCODE_NOP);
    codegen_emit_byte(codegen, OPCODE_NOP);
    
    // Patch the jump
    codegen_patch_jump(codegen, jump_offset);
    
    // Verify jump was patched (should jump 3 bytes forward)
    uint16_t jump = (chunk.code[jump_offset] << 8) | chunk.code[jump_offset + 1];
    ASSERT_EQ(jump, 3, "Jump should be 3 bytes");
    
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 17: Emit Loop Instruction
// ============================================================================
void test_emit_loop(void) {
    TEST("emit_loop");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    codegen->current_function = function_context_create(NULL, "test");
    codegen->current_function->chunk = &chunk;
    
    int loop_start = chunk.count;
    
    // Emit some instructions
    codegen_emit_byte(codegen, OPCODE_NOP);
    codegen_emit_byte(codegen, OPCODE_NOP);
    
    // Emit loop back to start
    codegen_emit_loop(codegen, loop_start);
    
    ASSERT_EQ(chunk.code[chunk.count - 3], OPCODE_LOOP, "Expected LOOP opcode");
    
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 18: Scope Management - Begin and End
// ============================================================================
void test_scope_management(void) {
    TEST("scope_management");
    
    CodeGenerator* codegen = codegen_create();
    codegen->current_function = function_context_create(NULL, "test");
    
    ASSERT_EQ(codegen->current_function->scope_depth, 0, "Initial scope depth should be 0");
    
    codegen_begin_scope(codegen);
    ASSERT_EQ(codegen->current_function->scope_depth, 1, "Scope depth should be 1");
    
    codegen_begin_scope(codegen);
    ASSERT_EQ(codegen->current_function->scope_depth, 2, "Scope depth should be 2");
    
    codegen_end_scope(codegen);
    ASSERT_EQ(codegen->current_function->scope_depth, 1, "Scope depth should be 1");
    
    codegen_end_scope(codegen);
    ASSERT_EQ(codegen->current_function->scope_depth, 0, "Scope depth should be 0");
    
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 19: Add Local Variable
// ============================================================================
void test_add_local(void) {
    TEST("add_local");
    
    CodeGenerator* codegen = codegen_create();
    codegen->current_function = function_context_create(NULL, "test");
    
    int idx1 = codegen_add_local(codegen, "x");
    ASSERT_EQ(idx1, 0, "First local should have index 0");
    ASSERT_EQ(codegen->current_function->local_count, 1, "Should have 1 local");
    
    int idx2 = codegen_add_local(codegen, "y");
    ASSERT_EQ(idx2, 1, "Second local should have index 1");
    ASSERT_EQ(codegen->current_function->local_count, 2, "Should have 2 locals");
    
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 20: Resolve Local Variable
// ============================================================================
void test_resolve_local(void) {
    TEST("resolve_local");
    
    CodeGenerator* codegen = codegen_create();
    codegen->current_function = function_context_create(NULL, "test");
    
    codegen_add_local(codegen, "x");
    codegen_add_local(codegen, "y");
    
    int idx_x = codegen_resolve_local(codegen, "x");
    ASSERT_EQ(idx_x, 0, "Variable 'x' should be at index 0");
    
    int idx_y = codegen_resolve_local(codegen, "y");
    ASSERT_EQ(idx_y, 1, "Variable 'y' should be at index 1");
    
    int idx_z = codegen_resolve_local(codegen, "z");
    ASSERT_EQ(idx_z, -1, "Variable 'z' should not be found");
    
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 21: Add Global Variable
// ============================================================================
void test_add_global(void) {
    TEST("add_global");
    
    CodeGenerator* codegen = codegen_create();
    
    int idx1 = codegen_add_global(codegen, "global_x");
    ASSERT_EQ(idx1, 0, "First global should have index 0");
    ASSERT_EQ(codegen->global_count, 1, "Should have 1 global");
    
    int idx2 = codegen_add_global(codegen, "global_y");
    ASSERT_EQ(idx2, 1, "Second global should have index 1");
    ASSERT_EQ(codegen->global_count, 2, "Should have 2 globals");
    
    // Adding same global again should return existing index
    int idx3 = codegen_add_global(codegen, "global_x");
    ASSERT_EQ(idx3, 0, "Duplicate global should return existing index");
    ASSERT_EQ(codegen->global_count, 2, "Should still have 2 globals");
    
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// TEST 22: Constant Pool Management
// ============================================================================
void test_constant_pool(void) {
    TEST("constant_pool");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    int idx1 = chunk_add_constant(&chunk, 3.14);
    ASSERT_EQ(idx1, 0, "First constant should have index 0");
    ASSERT_DOUBLE_EQ(chunk.constants.data[0], 3.14, "Constant value should be 3.14");
    
    int idx2 = chunk_add_constant(&chunk, 2.71);
    ASSERT_EQ(idx2, 1, "Second constant should have index 1");
    ASSERT_DOUBLE_EQ(chunk.constants.data[1], 2.71, "Constant value should be 2.71");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 23: Disassemble Simple Instruction
// ============================================================================
void test_disassemble_simple(void) {
    TEST("disassemble_simple");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    chunk_write(&chunk, OPCODE_RETURN, 1);
    
    // Just verify it doesn't crash
    int next_offset = codegen_disassemble_instruction(&chunk, 0);
    ASSERT_EQ(next_offset, 1, "Next offset should be 1");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 24: Disassemble Constant Instruction
// ============================================================================
void test_disassemble_constant(void) {
    TEST("disassemble_constant");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    int const_idx = chunk_add_constant(&chunk, 42.0);
    chunk_write(&chunk, OPCODE_CONSTANT, 1);
    chunk_write(&chunk, const_idx, 1);
    
    int next_offset = codegen_disassemble_instruction(&chunk, 0);
    ASSERT_EQ(next_offset, 2, "Next offset should be 2");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 25: Constant Folding Optimization
// ============================================================================
void test_constant_folding(void) {
    TEST("constant_folding");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    // Generate: CONSTANT 10, CONSTANT 20, ADD
    int idx1 = chunk_add_constant(&chunk, 10.0);
    int idx2 = chunk_add_constant(&chunk, 20.0);
    chunk_write(&chunk, OPCODE_CONSTANT, 1);
    chunk_write(&chunk, idx1, 1);
    chunk_write(&chunk, OPCODE_CONSTANT, 1);
    chunk_write(&chunk, idx2, 1);
    chunk_write(&chunk, OPCODE_ADD, 1);
    
    // Apply constant folding
    codegen_constant_folding(&chunk);
    
    // After optimization, should have folded to single constant
    // (Implementation may vary, just verify it doesn't crash)
    ASSERT_TRUE(chunk.count > 0, "Chunk should not be empty after optimization");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 26: Dead Code Elimination
// ============================================================================
void test_dead_code_elimination(void) {
    TEST("dead_code_elimination");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    // Generate: RETURN, NOP, NOP (dead code after RETURN)
    chunk_write(&chunk, OPCODE_RETURN, 1);
    chunk_write(&chunk, OPCODE_NOP, 1);
    chunk_write(&chunk, OPCODE_NOP, 1);
    
    int original_count = chunk.count;
    
    // Apply dead code elimination
    codegen_dead_code_elimination(&chunk);
    
    // Dead code should be marked as NOP
    ASSERT_EQ(chunk.count, original_count, "Chunk size should remain same");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 27: Peephole Optimization
// ============================================================================
void test_peephole_optimization(void) {
    TEST("peephole_optimization");
    
    Chunk chunk;
    chunk_init(&chunk);
    
    // Generate: DUP, POP (can be optimized away)
    chunk_write(&chunk, OPCODE_DUP, 1);
    chunk_write(&chunk, OPCODE_POP, 1);
    
    // Apply peephole optimization
    codegen_peephole_optimization(&chunk);
    
    // Verify optimization was applied (both should be NOP)
    ASSERT_TRUE(chunk.code[0] == OPCODE_NOP || chunk.code[0] == OPCODE_DUP, 
                "First instruction should be optimized or unchanged");
    
    chunk_free(&chunk);
    TEST_END;
}

// ============================================================================
// TEST 28: Error Handling - Invalid Operator
// ============================================================================
void test_error_invalid_operator(void) {
    TEST("error_invalid_operator");
    
    CodeGenerator* codegen = codegen_create();
    Chunk chunk;
    chunk_init(&chunk);
    
    // Create AST with invalid operator
    AstNode* left = create_literal_node(10.0);
    AstNode* right = create_literal_node(20.0);
    AstNode* invalid = create_binary_op_node("???", left, right);
    
    bool success = codegen_generate(codegen, invalid, &chunk);
    ASSERT_FALSE(success, "Should fail with invalid operator");
    ASSERT_TRUE(codegen->had_error, "Should report error");
    
    free_ast_node(invalid);
    chunk_free(&chunk);
    codegen_destroy(codegen);
    TEST_END;
}

// ============================================================================
// Main Test Runner
// ============================================================================
int main(void) {
    printf("========================================\n");
    printf("Bytecode Generation Test Suite\n");
    printf("========================================\n\n");
    
    // Run all tests
    test_codegen_create_destroy();
    test_generate_literal();
    test_generate_addition();
    test_generate_subtraction();
    test_generate_multiplication();
    test_generate_division();
    test_generate_modulo();
    test_generate_equality();
    test_generate_inequality();
    test_generate_greater_than();
    test_generate_greater_equal();
    test_generate_less_than();
    test_generate_less_equal();
    test_generate_complex_expression();
    test_emit_jump();
    test_patch_jump();
    test_emit_loop();
    test_scope_management();
    test_add_local();
    test_resolve_local();
    test_add_global();
    test_constant_pool();
    test_disassemble_simple();
    test_disassemble_constant();
    test_constant_folding();
    test_dead_code_elimination();
    test_peephole_optimization();
    test_error_invalid_operator();
    
    // Print summary
    printf("\n========================================\n");
    printf("Test Summary\n");
    printf("========================================\n");
    printf("Total tests:  %d\n", tests_run);
    printf("Passed:       %d\n", tests_passed);
    printf("Failed:       %d\n", tests_failed);
    printf("Success rate: %.1f%%\n", (tests_passed * 100.0) / tests_run);
    printf("========================================\n");
    
    return tests_failed == 0 ? 0 : 1;
}
