
// ===================================================================
// DESC: BDI Source→Bytecode→Execution Pipeline
//       Complete integration of lexer, parser, codegen, and VM
// ===================================================================
#ifndef BDI_PIPELINE_H
#define BDI_PIPELINE_H

#include "c23_compat.h"
#include "compiler/lexer/bci_lexer.h"
#include "compiler/parser/bci_parser.h"
#include "compiler/ast/bci_ast.h"
#include "compiler/codegen/codegen.h"
#include "vm/bci_chunk.h"
#include "vm/bci_vm.h"
#include "vm/vm.h"
#include <stdbool.h>
#include <stdint.h>

// Pipeline execution result
typedef struct {
    bool success;
    double result_value;        // For expressions that return a value
    const char* error_message;  // NULL if no error
    int error_line;             // Line number where error occurred
    
    // Statistics
    uint64_t compile_time_us;   // Compilation time in microseconds
    uint64_t execute_time_us;   // Execution time in microseconds
    size_t bytecode_size;       // Size of generated bytecode
    size_t constants_count;     // Number of constants
} PipelineResult;

// Pipeline configuration
typedef struct {
    bool enable_optimization;   // Enable bytecode optimizations
    bool enable_debug_info;     // Include debug information
    bool enable_gc;             // Enable garbage collection
    bool enable_jit;            // Enable JIT compilation (future)
    bool verbose;               // Print compilation/execution details
} PipelineConfig;

// Pipeline context (holds all compilation state)
typedef struct {
    Lexer lexer;
    Parser parser;
    CodeGenerator* codegen;
    Chunk* chunk;
    VM* vm;
    EnhancedVM* enhanced_vm;
    PipelineConfig config;
    PipelineResult result;
} PipelineContext;

// ============================================================================
// Pipeline API
// ============================================================================

// Initialize pipeline with default configuration
PipelineContext* pipeline_create(void);

// Initialize pipeline with custom configuration
PipelineContext* pipeline_create_with_config(PipelineConfig config);

// Destroy pipeline and free all resources
void pipeline_destroy(PipelineContext* ctx);

// Compile source code to bytecode
bool pipeline_compile(PipelineContext* ctx, const char* source);

// Execute compiled bytecode
bool pipeline_execute(PipelineContext* ctx);

// Compile and execute in one step (convenience function)
PipelineResult pipeline_run(const char* source);

// Compile and execute with custom configuration
PipelineResult pipeline_run_with_config(const char* source, PipelineConfig config);

// Get the last result
PipelineResult pipeline_get_result(const PipelineContext* ctx);

// Print pipeline statistics
void pipeline_print_stats(const PipelineContext* ctx);

// Disassemble compiled bytecode (for debugging)
void pipeline_disassemble(const PipelineContext* ctx);

// ============================================================================
// Helper Functions
// ============================================================================

// Create default pipeline configuration
PipelineConfig pipeline_default_config(void);

// Validate source code syntax (compile without execution)
bool pipeline_validate(const char* source, const char** error_message);

// Get bytecode from compiled source
Chunk* pipeline_get_bytecode(PipelineContext* ctx);

// Reset pipeline for reuse
void pipeline_reset(PipelineContext* ctx);

#endif // BDI_PIPELINE_H
