
#include "unicode_types.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Generate #embed header for a data file
bool generate_embed_header(const char *dat_filename, const char *header_filename, 
                           const char *array_name, size_t expected_size) {
    FILE *file = fopen(header_filename, "w");
    if (!file) {
        fprintf(stderr, "Failed to create %s\n", header_filename);
        return false;
    }
    
    // Write header guard
    fprintf(file, "#ifndef UNICODE_EMBED_H\n");
    fprintf(file, "#define UNICODE_EMBED_H\n\n");
    
    fprintf(file, "#include <stddef.h>\n");
    fprintf(file, "#include <stdint.h>\n\n");
    
    // Write #embed directive with compile-time assertions
    fprintf(file, "// Embedded Unicode data from %s\n", dat_filename);
    fprintf(file, "static const unsigned char %s[] = {\n", array_name);
    fprintf(file, "    #embed \"%s\"\n", dat_filename);
    fprintf(file, "};\n\n");
    
    // Add compile-time assertions
    fprintf(file, "// Compile-time assertions\n");
    fprintf(file, "_Static_assert(sizeof(%s) > 0, \"%s must not be empty\");\n", 
            array_name, array_name);
    
    if (expected_size > 0) {
        fprintf(file, "_Static_assert(sizeof(%s) == %zu, \"%s size mismatch\");\n",
                array_name, expected_size, array_name);
    }
    
    fprintf(file, "\n#endif // UNICODE_EMBED_H\n");
    
    fclose(file);
    
    printf("Generated embed header: %s\n", header_filename);
    return true;
}

// Generate master embed header that includes all data files
bool generate_master_embed_header(const char *output_dir) {
    char filename[512];
    snprintf(filename, sizeof(filename), "%s/unicode_embed.h", output_dir);
    
    FILE *file = fopen(filename, "w");
    if (!file) {
        fprintf(stderr, "Failed to create %s\n", filename);
        return false;
    }
    
    fprintf(file, "#ifndef UNICODE_EMBED_MASTER_H\n");
    fprintf(file, "#define UNICODE_EMBED_MASTER_H\n\n");
    
    fprintf(file, "#include <stddef.h>\n");
    fprintf(file, "#include <stdint.h>\n\n");
    
    fprintf(file, "// Unicode 17.0.0 Embedded Data\n");
    fprintf(file, "// Generated by BDI Unicode Data Pipeline\n\n");
    
    // Embed basic data
    fprintf(file, "// Basic Unicode data (ranges, classes)\n");
    fprintf(file, "static const unsigned char unicode_basic_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_basic.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_basic_data) > 0, \"Basic data must not be empty\");\n\n");
    
    // Embed math data
    fprintf(file, "// Math symbols data\n");
    fprintf(file, "static const unsigned char unicode_math_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_math.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_math_data) > 0, \"Math data must not be empty\");\n\n");
    
    // Embed properties data
    fprintf(file, "// Character properties data\n");
    fprintf(file, "static const unsigned char unicode_props_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_props.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_props_data) > 0, \"Props data must not be empty\");\n\n");
    
    // Embed emoji data
    fprintf(file, "// Emoji data\n");
    fprintf(file, "static const unsigned char unicode_emoji_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_emoji.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_emoji_data) > 0, \"Emoji data must not be empty\");\n\n");
    
    // Embed collation data
    fprintf(file, "// Collation data\n");
    fprintf(file, "static const unsigned char unicode_collation_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_collation.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_collation_data) > 0, \"Collation data must not be empty\");\n\n");
    
    // Embed IDNA data
    fprintf(file, "// IDNA data\n");
    fprintf(file, "static const unsigned char unicode_idna_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_idna.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_idna_data) > 0, \"IDNA data must not be empty\");\n\n");
    
    // Embed Unihan data
    fprintf(file, "// Unihan data\n");
    fprintf(file, "static const unsigned char unicode_han_data[] = {\n");
    fprintf(file, "    #embed \"../data/unicode_han.dat\"\n");
    fprintf(file, "};\n");
    fprintf(file, "_Static_assert(sizeof(unicode_han_data) > 0, \"Han data must not be empty\");\n\n");
    
    fprintf(file, "#endif // UNICODE_EMBED_MASTER_H\n");
    
    fclose(file);
    
    printf("Generated master embed header: %s\n", filename);
    return true;
}

