#ifndef UNICODE_EMBED_MASTER_H
#define UNICODE_EMBED_MASTER_H

#include <stddef.h>
#include <stdint.h>

// Unicode 17.0.0 Embedded Data
// Generated by BDI Unicode Data Pipeline

// Basic Unicode data (ranges, classes)
static const unsigned char unicode_basic_data[] = {
    #embed "../data/unicode_basic.dat"
};
_Static_assert(sizeof(unicode_basic_data) > 0, "Basic data must not be empty");

// Math symbols data
static const unsigned char unicode_math_data[] = {
    #embed "../data/unicode_math.dat"
};
_Static_assert(sizeof(unicode_math_data) > 0, "Math data must not be empty");

// Character properties data
static const unsigned char unicode_props_data[] = {
    #embed "../data/unicode_props.dat"
};
_Static_assert(sizeof(unicode_props_data) > 0, "Props data must not be empty");

// Emoji data
static const unsigned char unicode_emoji_data[] = {
    #embed "../data/unicode_emoji.dat"
};
_Static_assert(sizeof(unicode_emoji_data) > 0, "Emoji data must not be empty");

// Collation data
static const unsigned char unicode_collation_data[] = {
    #embed "../data/unicode_collation.dat"
};
_Static_assert(sizeof(unicode_collation_data) > 0, "Collation data must not be empty");

// IDNA data
static const unsigned char unicode_idna_data[] = {
    #embed "../data/unicode_idna.dat"
};
_Static_assert(sizeof(unicode_idna_data) > 0, "IDNA data must not be empty");

// Unihan data
static const unsigned char unicode_han_data[] = {
    #embed "../data/unicode_han.dat"
};
_Static_assert(sizeof(unicode_han_data) > 0, "Han data must not be empty");

#endif // UNICODE_EMBED_MASTER_H
